config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles, only: [:new, :edit, :create, :update]

  resources :categories
  root to: 'pages#home'



  resources :users, only: [:show]
  resources :events, except: [:destroy]
  resources :events do
  resources :bookings, only: [:create]
  end
  namespace :api do
     resources :events
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :categories, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :guests, through: :bookings, source: :user




  validates :name, presence: true
  validates :description, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :starts_at, presence: true
  validates :ends_at, presence: true


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events,  dependent: :destroy
  has_one :profile, dependent: :destroy
  has_and_belongs_to_many :categories, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :booked_events, through: :bookings, source: :event

   def has_profile?
     profile.present? && profile.persisted?
   end
   def full_name
     profile.full_name
   end

 end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    render status: 200, json: {
      events: Event.all
    }.to_json
  end
  def show
    event = Event.find(params[:id])

    render status: 200, json: {
      event: event
    }.to_json
  end
  def create
   event = Event.new(event_params)

   if event.save
     render status: 201, json: {
       message: "Event successfully created",
       event: event
     }.to_json
   else
     render status: 422, json: {
       errors: event.errors
     }.to_json
   end
 end

  private

  def event_params
    params.require(:event)
    .permit(:name, :description, :location, :price,
    :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, theme_ids:[])

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
  end

  def new

    @event = current_user.events.build
  end

  def form
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: "Event form"
    else
      render :new
    end
  end

  def edit_event; end
def create
  @event = current_user.events.build(event_params)

  if @event.save
    image_params.each do |image|
      @event.photos.create(image: image)

redirect_to_edit_path(@event) notice: "Event Successfully created"
end
end
end


  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event updated"
    else
      render :edit
    end
  end

  private
   def set_categories
     @categories = Category.all
   end

   def set_event
     @event = Event.find(params[:id])
   end

   def image_params
     params[:images].present? ? params.require(:images) : []
   end

   def event_params
     params
       .require(:event)
       .permit(
       :name, :description, :location, :price, :capacity, :includes_food, :includes_drinks,
       :starts_at, :ends_at, :active, category_ids: [])

   end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end
  def show
    @category = @event.categories
  end
  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <div class="form-group">
    <label>Event Type </label>
    <%= f.select :description, [["Canals", "Canals"], ["Walking", "Walking"], ["Club & Beach", "Club & Beacht"]], id: "event_type", prompt: "Select event type", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= f.select :location, [["Group","Group"], ["Private", "Private"], ["Shared", "Shared"]], prompt: "Select event type", class: "form-control" %>
  </div>

<label>Amenities</label>
  <div class="form-group">
    <%= f.check_box :location %> Location
  </div>

  <div class="form-group">
    <%= f.check_box :capacity %> capacity
  </div>

  <div class="form-group">
    <%= f.check_box :includes_food %> Food
  </div>
  <div class="form-group">
    <%= f.check_box :includes_drinks %> Drinks
  </div>

  <div class="form-group">
    <label>Daily Price</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :price, placeholder: "eg. 100", class: "form-control" %>
    </div>
  </div>

  <label>Categories</label>

<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
  <div class="form-group">
    <%= b.check_box(class: "check_box") %> <%= b.object.name %>
  </div>
<% end %>

  <label>Publish this place?</label>

  <div class="form-group">
    <%= f.check_box :active %> Active
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit_event.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new place", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/new_event.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"> <%= @event %></div>

  <div class="panel-body">

    <p>Address: <%= @event %></p>
    <p>Host: <%= @event %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Home Type: <%= @event %></p>
    <p><%= @event %> <%= @event = 1 ? "Walking in Holland" : "Walking in Holland" %></p>
    <p><%= @event %> <%= @event = 1 ? "Cool" : "Cool" %></p>


    <!-- About -->
    <h4>About</h4>
    <p><%= @event %></p>

    <!-- Amenities -->
    <h4>More about event</h4>
    <ul class="amenities">
      <li><%= !@event ? ("<s>Location</s>").html_safe : "Location" %></li>
      <li><%= !@event ? ("<del>Price</del>").html_safe : "Price" %></li>
      <li><%= !@event ? ("<del>Capacity</del>").html_safe : "Capacity" %></li>
      <li><%= !@event ? ("<del>Includes_food</del>").html_safe : "Includes_food" %></li>
      <li><%= !@event ? ("<del>Includes_drinks</del>").html_safe : "Includes_drinks" %></li>
    </ul>

  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>
<!-- Categories -->
<h4>Categories</h4>
<% @categories.each do |category| %>
  <span class="label label-success"><%= category.name %></span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to this awesome page</h1>
<p>Find me in app/views/pages/home.html.erb to learn more about rails</p>
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-primary btn-lg">Left</button>
  <button type="button" class="btn btn-primary btn-lg">Middle</button>
  <button type="button" class="btn btn-primary btn-lg">Right</button>
  <button type="button" class="btn btn-primary btn-lg">Large button</button>
  <p class="bg-success"></p>

</div>

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="//www.youtube.com/embed/48OJbbI0DfE" allowfullscreen></iframe>
</div>
<div class="container-fluid">
  <!-- A fluid container that uses the full witdh -->
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>

          <ul class="dropdown-menu">
            <li><%= link_to "Event", events_path %></li>
            <li role="separator" class="divider"></li>

            <% if current_user.has_profile? %>

            <ul class="dropdown-menu">
             <li><%= link_to "Your Events", events_path %></li>
             <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
             <li role="separator" class="divider"></li>
             <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
           </ul>


              <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
            <% else %>
              <li><%= link_to "Create Profile", new_profile_path %></li>
            <% end %>
            <li><%= link_to "Edit Password", edit_user_registration_path %></li>

            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>

        </li>

          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_validation_errors.html.erb
  validates :name, presence: true
  validates :description, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :starts_at, presence: true
  validates :ends_at, presence: true